//! 語のつながり方による検出の誤り (会社名と人名の連結、敬称の連続、英字・長音の直後の番号など) の退行テスト。
//! 期待値は既定の設定 (テンプレート `<{label}_{n}>`) での出力。値はすべて架空 (ドメインは架空の社名、住所は架空の町名)。

use sumiveil_core::{engine::mask_text, Config};

const CASES: &[(&str, &str)] = &[
    (r#"アオバ商事株式会社田中様"#, r#"<COMPANY_1><NAME_1>様"#),
    (r#"アオバ商事株式会社の田中様"#, r#"<COMPANY_1>の<NAME_1>様"#),
    (r#"アオバ商事株式会社 営業部 田中太郎様"#, r#"<COMPANY_1> 営業部 <NAME_1>様"#),
    (r#"株式会社アオバ商事 田中太郎"#, r#"<COMPANY_1> <NAME_1>"#),
    (r#"株式会社アオバ商事田中太郎"#, r#"<COMPANY_1><NAME_1>"#),
    (r#"(株)アオバ商事田中"#, r#"<COMPANY_1>"#),
    (r#"㈱アオバ田中様"#, r#"<COMPANY_1><NAME_1>様"#),
    (r#"アオバ商事(株)田中様"#, r#"<COMPANY_1><NAME_1>様"#),
    (r#"営業部長田中様"#, r#"営業部長<NAME_1>様"#),
    (r#"田中部長"#, r#"<NAME_1>部長"#),
    (r#"田中太郎さんと佐藤花子さん"#, r#"<NAME_1>さんと<NAME_2>さん"#),
    (r#"田中さん佐藤さん"#, r#"<NAME_1>さん<NAME_2>さん"#),
    (r#"田中様、佐藤様"#, r#"<NAME_1>様、<NAME_2>様"#),
    (r#"山田株式会社"#, r#"<COMPANY_1>"#),
    (r#"株式会社山田"#, r#"<COMPANY_1>"#),
    (r#"田中町1-2-3"#, r#"<ADDRESS_1>"#),
    (r#"東京都架空市桜台1丁目2-3田中様方"#, r#"<ADDRESS_1><NAME_1>様方"#),
    (r#"TEL03-1234-5678FAX03-1234-5679"#, r#"TEL<PHONE_1>FAX<PHONE_2>"#),
    (r#"電話090-1234-5678メールtanaka@aobashoji.co.jp"#, r#"電話<PHONE_1>メール<EMAIL_1>"#),
    (r#"2026年10月1日田中様"#, r#"2026年10月1日<NAME_1>様"#),
    (r#"090-1234-5678 123-4567"#, r#"<PHONE_1> <POSTAL_1>"#),
    (r#"担当: アオバ商事株式会社営業部 田中"#, r#"担当: <COMPANY_1>営業部 <NAME_1>"#),
    (r#"TEL:03-1234-5678"#, r#"TEL:<PHONE_1>"#),
    (r#"TEL03-1234-5678"#, r#"TEL<PHONE_1>"#),
    (r#"Tel.03-1234-5678"#, r#"Tel.<PHONE_1>"#),
    (r#"携帯09012345678"#, r#"携帯<PHONE_1>"#),
    (r#"IP192.168.10.5で"#, r#"IP<IPV4_1>で"#),
    (r#"C:\Users\tanaka\Desktop"#, r#"C:\Users\<USER_1>\Desktop"#),
    (r#"password=Abc12345"#, r#"password=<PASSWORD_1>"#),
    (r#"パスワードはAbc12345です"#, r#"パスワードは<PASSWORD_1>です"#),
    (r#"パスワード：Abc12345、ID：tanaka"#, r#"パスワード：<PASSWORD_1>、ID：tanaka"#),
    (r#"マイナンバー123456789018"#, r#"マイナンバー<MY_NUMBER_1>"#),
    (r#"マイナンバー 1234 5678 9018"#, r#"マイナンバー <MY_NUMBER_1>"#),
    (r#"口座番号1234567"#, r#"口座番号<BANK_ACCOUNT_1>"#),
    (r#"生年月日1990年1月2日"#, r#"生年月日<BIRTHDATE_1>"#),
    (r#"1990/01/02生まれ"#, r#"<BIRTHDATE_1>生まれ"#),
    (r#"1990年1月2日生"#, r#"<BIRTHDATE_1>生"#),
    (r#"tanaka@aobashoji.co.jp"#, r#"<EMAIL_1>"#),
    (r#"メールtanaka@aobashoji.co.jp"#, r#"メール<EMAIL_1>"#),
    (r#"宛先はtanaka@aobashoji.co.jpです"#, r#"宛先は<EMAIL_1>です"#),
    (r#"tanaka@aobashoji.co.jp田中"#, r#"<EMAIL_1>田中"#),
    (r#"IP 192.168.10.5"#, r#"IP <IPV4_1>"#),
    (r#"192.168.10.5:8080"#, r#"<IPV4_1>:8080"#),
    (r#"パスワード:Abc12345です。"#, r#"パスワード:<PASSWORD_1>です。"#),
    (r#"個人番号：123456789012"#, r#"個人番号：123456789012"#),
    (r#"TEL 03-1234-5678 FAX 03-1234-5679"#, r#"TEL <PHONE_1> FAX <PHONE_2>"#),
    (r#"03-1234-5678/03-1234-5679"#, r#"<PHONE_1>/<PHONE_2>"#),
    (r#"田中課長より"#, r#"<NAME_1>課長より"#),
    (r#"課長の田中"#, r#"課長の<NAME_1>"#),
    (r#"田中先生"#, r#"<NAME_1>先生"#),
    (r#"田中殿"#, r#"<NAME_1>殿"#),
    (r#"田中君"#, r#"<NAME_1>君"#),
    (r#"田中氏"#, r#"<NAME_1>氏"#),
    (r#"田中太郎氏"#, r#"<NAME_1>氏"#),
    (r#"氏名：田中太郎"#, r#"氏名：<NAME_1>"#),
    (r#"担当：田中"#, r#"担当：<NAME_1>"#),
    (r#"担当者 田中"#, r#"担当者 <NAME_1>"#),
    (r#"差出人: 田中太郎"#, r#"差出人: <NAME_1>"#),
    (r#"田中様佐藤様"#, r#"<NAME_1>様<NAME_2>様"#),
    (r#"田中様・佐藤様"#, r#"<NAME_1>様・<NAME_2>様"#),
    (r#"林さん"#, r#"<NAME_1>さん"#),
    (r#"森さんと林さん"#, r#"<NAME_1>さんと<NAME_2>さん"#),
    (r#"小林さん"#, r#"<NAME_1>さん"#),
    (r#"中さん"#, r#"中さん"#),
    (r#"タナカさん"#, r#"<NAME_1>さん"#),
    (r#"タナカ タロウ様"#, r#"<NAME_1>様"#),
    (r#"Tanaka Taro様"#, r#"<NAME_1>様"#),
    (r#"Mr. Smith"#, r#"Mr. <NAME_1>"#),
    (r#"Dear John,"#, r#"Dear <NAME_1>,"#),
    (r#"From: John Smith <js@aobashoji.co.jp>"#, r#"From: <NAME_1> <<EMAIL_1>>"#),
    (r#"CC: 田中様"#, r#"CC: <NAME_1>様"#),
    (r#"株式会社アオバ商事御中"#, r#"<COMPANY_1>御中"#),
    (r#"アオバ商事株式会社御中"#, r#"<COMPANY_1>御中"#),
    (r#"株式会社アオバ商事様"#, r#"<COMPANY_1>様"#),
    (r#"株式会社アオバ商事営業部"#, r#"<COMPANY_1>営業部"#),
    (r#"株式会社アオバ商事営業部田中様"#, r#"<COMPANY_1>営業部<NAME_1>様"#),
    (r#"アオバ商事株式会社東京支店"#, r#"<COMPANY_1>東京支店"#),
    (r#"アオバ商事株式会社東京支店長田中"#, r#"<COMPANY_1>東京支店長<NAME_1>"#),
    (r#"株式会社アオバ商事と株式会社ミナト技研"#, r#"<COMPANY_1>と<COMPANY_2>"#),
    (r#"アオバ商事株式会社とミナト技研株式会社"#, r#"<COMPANY_1>と<COMPANY_2>"#),
    (r#"弊社アオバ商事株式会社では"#, r#"弊社<COMPANY_1>では"#),
    (r#"当社は株式会社です"#, r#"当社は株式会社です"#),
    (r#"株式会社とは何か"#, r#"株式会社とは何か"#),
    (r#"株式会社化する"#, r#"株式会社化する"#),
    (r#"株式会社の設立手続き"#, r#"株式会社の設立手続き"#),
    (r#"株式会社等"#, r#"株式会社等"#),
    (r#"株式会社アオバ商事代表取締役田中太郎"#, r#"<COMPANY_1>代表取締役<NAME_1>"#),
    (r#"代表取締役社長 田中太郎"#, r#"代表取締役社長 <NAME_1>"#),
    (r#"一般社団法人アオバ協会理事長田中"#, r#"<COMPANY_1>理事長<NAME_1>"#),
    (r#"医療法人アオバ会田中クリニック"#, r#"<COMPANY_1>"#),
    (r#"アオバ株式会社社長"#, r#"<COMPANY_1>社長"#),
    (r#"アオバ商事株式会社株式会社ミナト"#, r#"<COMPANY_1><COMPANY_2>"#),
    (r#"（株）アオバ商事"#, r#"<COMPANY_1>"#),
    (r#"アオバ商事（株）"#, r#"<COMPANY_1>"#),
    (r#"アオバ商事㈱"#, r#"<COMPANY_1>"#),
    (r#"contract with Example Widgets Inc. and Minato LLC"#, r#"contract with <COMPANY_1> and <COMPANY_2>"#),
    (r#"０９０－１２３４－５６７８"#, r#"<PHONE_1>"#),
    (r#"090ー1234ー5678"#, r#"<PHONE_1>"#),
    (r#"(03)1234-5678"#, r#"<PHONE_1>"#),
    (r#"+81-90-1234-5678"#, r#"<PHONE_1>"#),
    (r#"０３−１２３４−５６７８まで"#, r#"<PHONE_1>まで"#),
    (r#"ｔａｎａｋａ＠ａｏｂａｓｈｏｊｉ．ｃｏ．ｊｐ"#, r#"<EMAIL_1>"#),
    (r#"tanaka＠aobashoji.co.jp"#, r#"<EMAIL_1>"#),
    (r#"tanaka(at)aobashoji.co.jp"#, r#"<EMAIL_1>"#),
    (r#"tanaka%40aobashoji.co.jp"#, r#"<EMAIL_1>"#),
    (r#"ﾀﾅｶ様"#, r#"<NAME_1>様"#),
    (r#"田中　太郎様"#, r#"<NAME_1>様"#),
    (r#""田中太郎",090-1234-5678,tanaka@aobashoji.co.jp"#, r#""<NAME_1>",<PHONE_1>,<EMAIL_1>"#),
    (r#"{"name":"田中太郎","tel":"090-1234-5678"}"#, r#"{"name":"<NAME_1>","tel":"<PHONE_1>"}"#),
    (r#"<td>田中様</td><td>090-1234-5678</td>"#, r#"<td><NAME_1>様</td><td><PHONE_1></td>"#),
    (r#"〒１２３－４５６７"#, r#"<POSTAL_1>"#),
    (r#"郵便番号1234567"#, r#"郵便番号<POSTAL_1>"#),
    (r#"お疲れ様です"#, r#"お疲れ様です"#),
    (r#"皆様へ"#, r#"皆様へ"#),
    (r#"お客様各位"#, r#"お客様各位"#),
    (r#"ご担当者様"#, r#"ご担当者様"#),
    (r#"奥様によろしく"#, r#"奥様によろしく"#),
    (r#"部長さん"#, r#"部長さん"#),
    (r#"大家さん"#, r#"大家さん"#),
    (r#"八百屋さん"#, r#"八百屋さん"#),
    (r#"神様仏様"#, r#"神様仏様"#),
    (r#"王様ゲーム"#, r#"王様ゲーム"#),
    (r#"同様に"#, r#"同様に"#),
    (r#"仕様です"#, r#"仕様です"#),
    (r#"様々な"#, r#"様々な"#),
    (r#"新宿駅の田中さん"#, r#"新宿駅の<NAME_1>さん"#),
    (r#"東京都千代田区丸の内1-1-1"#, r#"<ADDRESS_1>"#),
    (r#"東京都千代田区丸の内1-1-1丸の内ビル10階"#, r#"<ADDRESS_1>"#),
    (r#"千代田区丸の内1丁目1番1号"#, r#"<ADDRESS_1>"#),
    (r#"大阪市北区架空町1-2-3"#, r#"<ADDRESS_1>"#),
    (r#"架空市桜台一丁目二番三号"#, r#"<ADDRESS_1>"#),
    (r#"1-2-3 Sakuradai, Kaku-shi, Tokyo 123-4567"#, r#"<ADDRESS_1>"#),
    (r#"Version 1.2.3"#, r#"Version 1.2.3"#),
    (r#"バージョン1.2.3"#, r#"バージョン1.2.3"#),
    (r#"第1-2-3条"#, r#"第1-2-3条"#),
    (r#"コールセンター03-1234-5678"#, r#"コールセンター<PHONE_1>"#),
    (r#"サポートセンター0312345678"#, r#"サポートセンター<PHONE_1>"#),
    (r#"カード番号ー4111111111111111"#, r#"カード番号ー4111111111111111"#),
    (r#"サーバー192.168.1.10"#, r#"サーバー<IPV4_1>"#),
    (r#"取引先アオバ商事株式会社"#, r#"取引先<COMPANY_1>"#),
    (r#"2024年度アオバ商事株式会社"#, r#"2024年度<COMPANY_1>"#),
    (r#"Call +1 415-555-0132 2024 edition"#, r#"Call <PHONE_1> 2024 edition"#),
    (r#"東京都から10名参加"#, r#"東京都から10名参加"#),
    (r#"東京都の第1会議室"#, r#"東京都の第1会議室"#),
    (r#"大阪府で3件"#, r#"大阪府で3件"#),
    (r#"田中横浜市中区架空町1-2-3在住"#, r#"田中<ADDRESS_1>在住"#),
    (r#"担当田中横浜市架空町1-2-3"#, r#"担当<NAME_1><ADDRESS_1>"#),
    (r#"株式会社アオバ商事(東京都架空市桜台1-2-3)"#, r#"<COMPANY_1>(<ADDRESS_1>)"#),
    (r#"アオバ商事株式会社田中太郎(090-1234-5678)"#, r#"<COMPANY_1><NAME_1><PHONE_1>)"#),
    (r#"sample test株式会社"#, r#"<COMPANY_1>"#),
    (r#"Sample Test株式会社"#, r#"<COMPANY_1>"#),
    (r#"sample test 株式会社"#, r#"<COMPANY_1>"#),
    (r#"株式会社sample test"#, r#"<COMPANY_1>"#),
    (r#"株式会社 Sample Test"#, r#"<COMPANY_1>"#),
    (r#"Sample Test株式会社の田中様"#, r#"<COMPANY_1>の<NAME_1>様"#),
    (r#"アオバ 商事株式会社"#, r#"<COMPANY_1>"#),
    (r#"アオバ　商事株式会社"#, r#"<COMPANY_1>"#),
    (r#"株式会社アオバ 商事"#, r#"<COMPANY_1>"#),
    (r#"株式会社アオバ 商事 田中様"#, r#"<COMPANY_1> <NAME_1>様"#),
    (r#"ABC Systems株式会社"#, r#"<COMPANY_1>"#),
    (r#"株式会社ABC Systems Japan"#, r#"<COMPANY_1>"#),
    (r#"Aoba-Tech株式会社"#, r#"<COMPANY_1>"#),
    (r#"Aoba.Tech株式会社"#, r#"<COMPANY_1>"#),
    (r#"アオバ&ミナト株式会社"#, r#"<COMPANY_1>"#),
    (r#"ＡＢＣ　システムズ株式会社"#, r#"<COMPANY_1>"#),
    (r#"アオバ商事 株式会社 田中様"#, r#"<COMPANY_1> <NAME_1>様"#),
    (r#"contract with Sample Test株式会社"#, r#"contract with <COMPANY_1>"#),
    (r#"担当 アオバ商事株式会社"#, r#"担当 <COMPANY_1>"#),
    (r#"株式会社田中製作所"#, r#"<COMPANY_1>"#),
    (r#"株式会社山田商店田中様"#, r#"<COMPANY_1><NAME_1>様"#),
    // 敬称・項目名の無い姓 (並び + 人を表す語、姓 + 助詞 + 人の行動)
    (r#"田中・佐藤・鈴木の3名"#, r#"<NAME_1>・<NAME_2>・<NAME_3>の3名"#),
    (r#"出席者: 田中、佐藤、鈴木"#, r#"出席者: <NAME_1>、<NAME_2>、<NAME_3>"#),
    (r#"田中と佐藤が出席しました。"#, r#"<NAME_1>と<NAME_2>が出席しました。"#),
    (r#"本日田中が担当します。"#, r#"本日<NAME_1>が担当します。"#),
    (r#"山本に連絡してください。"#, r#"<NAME_1>に連絡してください。"#),
    (r#"以上、よろしくお願いします。田中より"#, r#"以上、よろしくお願いします。<NAME_1>より"#),
    (r#"担当は田中です"#, r#"担当は<NAME_1>です"#),
    (r#"営業部の田中に確認"#, r#"営業部の<NAME_1>に確認"#),
    // 姓と同じ表記の一般語・地名は、文脈が無ければ人名にしない
    (r#"平野部の森林を保全する。"#, r#"平野部の森林を保全する。"#),
    (r#"森林・平野・山地などの地形"#, r#"森林・平野・山地などの地形"#),
    (r#"出口から入場してください。"#, r#"出口から入場してください。"#),
    (r#"石川に連絡します。"#, r#"石川に連絡します。"#),
    (r#"中野に出張します。"#, r#"中野に出張します。"#),
];

/// strict プロファイル相当 (辞書のしきい値 0.5・最低信頼度 0.4) で、人名を書く位置にある姓だけも検出する。
const STRICT_CASES: &[(&str, &str)] = &[
    ("田中", "<NAME_1>"),
    ("東京都架空市桜台1-2-3 アオバビル5F 田中", "<ADDRESS_1> <NAME_1>"),
    ("社員番号A12345の田中", "社員番号<EMPLOYEE_ID_1>の<NAME_1>"),
    ("出口から入場してください。", "出口から入場してください。"),
    ("平野部の森林を保全する。", "平野部の森林を保全する。"),
    ("森林・平野・山地などの地形", "森林・平野・山地などの地形"),
];

#[test]
fn bare_surnames_in_strict_settings() {
    let mut cfg = Config::default();
    cfg.names.dictionary_threshold = 0.5;
    cfg.masking.min_confidence = 0.4;
    for (input, expected) in STRICT_CASES {
        assert_eq!(&mask_text(&cfg, input).output, expected, "{input}");
    }
}

#[test]
fn combinations_are_masked_as_expected() {
    let cfg = Config::default();
    let mut failures = vec![];
    for (input, expected) in CASES {
        let got = mask_text(&cfg, input).output;
        if got != *expected {
            failures.push(format!("{input}\n  expected: {expected}\n  got:      {got}"));
        }
    }
    assert!(failures.is_empty(), "{} case(s) differ:\n{}", failures.len(), failures.join("\n"));
}
